### ISSUE TITLE
add tracking options

### ISSUE THREAD

**Issue by ansib** [basetwode/cypetulip#90]
- [ ] https://umami.is/
- [ ] https://pypi.org/project/django-matomo/
- [ ] [django-anyalytical](https://github.com/jazzband/django-analytical)
